// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H


namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Building - 
  class Building : public state::StaticElement {
    // Operations
  public:
    Building ();
    ~Building ();
    // Setters and Getters
  };

};

#endif
