// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H


namespace state {
  class MobileElement;
  class StaticELement;
}

#include "StaticELement.h"

namespace state {

  /// class Building - 
  class Building : public state::StaticELement {
    // Attributes
  protected:
    int MinionNumber     = 0;
    int Team;
    // Operations
  public:
    void MinionGeneration ();
    void Attack (const MobileElement& other);
    int setTeam ();
    int getTeam ();
    // Setters and Getters
    int getMinionNumber() const;
    void setMinionNumber(int MinionNumber);
  };

};

#endif
