// Generated by dia2code
#ifndef STATE__BUILDING__H
#define STATE__BUILDING__H


namespace state {
  class MobileElement;
  class StaticELement;
}

#include "StaticELement.h"

namespace state {

  /// class Building - 
  class Building : public state::StaticELement {
    // Attributes
  protected:
    int m_MinionNumber     = 0;
    int m_Team;
    // Operations
  public:
    void MinionGeneration ();
    void Attack (const MobileElement& other);
    int setTeam ();
    int getTeam ();
    // Setters and Getters
    int getM_MinionNumber() const;
    void setM_MinionNumber(int m_MinionNumber);
    int getM_Team() const;
    void setM_Team(int m_Team);
  };

};

#endif
