// Generated by dia2code
#ifndef STATE__COEUR__H
#define STATE__COEUR__H


namespace state {
  class Decor;
}

#include "Decor.h"

namespace state {

  /// class Coeur - 
  class Coeur : public state::Decor {
    // Operations
  public:
    Coeur ();
    ~Coeur ();
    // Setters and Getters
  };

};

#endif
