// Generated by dia2code
#ifndef STATE__COMMANDCENTER__H
#define STATE__COMMANDCENTER__H


namespace state {
  class Building;
}

#include "Building.h"

namespace state {

  /// class CommandCenter - 
  class CommandCenter : public state::Building {
    // Attributes
  protected:
    int Life;
    // Operations
  public:
    CommandCenter ();
    ~CommandCenter ();
    void getDamage (int damage);
    bool isAlive ();
    // Setters and Getters
    int getLife() const;
    void setLife(int Life);
  };

};

#endif
