// Generated by dia2code
#ifndef STATE__COMMANDTOWER__H
#define STATE__COMMANDTOWER__H


namespace state {
  class Building;
}

#include "Building.h"

namespace state {

  /// class CommandTower - 
  class CommandTower : public state::Building {
    // Operations
  public:
    CommandTower ();
    ~CommandTower ();
    void getStatus ();
    /// 	
    /// @param Team		(???) 
    CommandTower (int Team);
    // Setters and Getters
  };

};

#endif
