// Generated by dia2code
#ifndef STATE__COMMANDTOWER__H
#define STATE__COMMANDTOWER__H


namespace state {
  class Building;
}

#include "Building.h"

namespace state {

  /// class CommandTower - 
  class CommandTower : public state::Building {
    // Attributes
  public:
     ;
    // Operations
  public:
    CommandTower ();
    TypeId const getTypeId ();
    // Setters and Getters
  };

};

#endif
