// Generated by dia2code
#ifndef STATE__DECOR__H
#define STATE__DECOR__H


namespace state {
  class StaticElement;
}

#include "StaticElement.h"

namespace state {

  /// class Decor - 
  class Decor : public state::StaticElement {
    // Operations
  public:
    Decor ();
    ~Decor ();
    // Setters and Getters
  };

};

#endif
