// Generated by dia2code
#ifndef STATE__DECORID__H
#define STATE__DECORID__H


namespace state {
  class Decor;
}

#include "Decor.h"

namespace state {

  enum DecorId {
    ROCK     = 1,
    WATER     = 2,
    TREE     = 3,
    PATH     = 4
  };

};

#endif
