// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int m_x     = 0;
    int m_y     = 0;
    bool m_Team;
    // Operations
  public:
    Element ();
    ~Element ();
    TypeId const getTypeId ();
    bool const isStatic ();
    bool const equals (const Element& other);
    bool const getTeam ();
    // Setters and Getters
    int getM_x() const;
    void setM_x(int m_x);
    int getM_y() const;
    void setM_y(int m_y);
    bool getM_Team() const;
    void setM_Team(bool m_Team);
  };

};

#endif
