// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H

#include <string>

#include "TypeId.h"

namespace state {

  /// class Element - 
  class Element {
    // Associations
    // Attributes
  protected:
    TypeId typeId;
    std::string Name;
    int PosX;
    int PosY;
    // Operations
  public:
    Element ();
    ~Element ();
    // Setters and Getters
    TypeId getTypeId() const;
    void setTypeId(TypeId typeId);
    const std::string& getName() const;
    void setName(const std::string& Name);
    int getPosX() const;
    void setPosX(int PosX);
    int getPosY() const;
    void setPosY(int PosY);
  };

};

#endif
