// Generated by dia2code
#ifndef STATE__ELEMENT__H
#define STATE__ELEMENT__H


namespace state {
  class Element;
}

namespace state {

  /// class Element - 
  class Element {
    // Attributes
  protected:
    int x     = 0;
    int y     = 0;
    bool Team;
    // Operations
  public:
    Element ();
    ~Element ();
    TypeId const getTypeId ();
    bool const isStatic ();
    bool const equals (const Element& other);
    bool const getTeam ();
    // Setters and Getters
    int getX() const;
    void setX(int x);
    int getY() const;
    void setY(int y);
    void setTeam(bool Team);
  };

};

#endif
