// Generated by dia2code
#ifndef STATE__ENIRIPSA__H
#define STATE__ENIRIPSA__H


namespace state {
  class Hero;
}

#include "Hero.h"

namespace state {

  /// class Eniripsa - 
  class Eniripsa : public state::Hero {
    // Operations
  public:
    Eniripsa ();
    ~Eniripsa ();
    Eniripsa (int Team);
    // Setters and Getters
  };

};

#endif
