// Generated by dia2code
#ifndef STATE__ENUTROF__H
#define STATE__ENUTROF__H


namespace state {
  class Hero;
}

#include "Hero.h"

namespace state {

  /// class Enutrof - 
  class Enutrof : public state::Hero {
    // Operations
  public:
    Enutrof ();
    ~Enutrof ();
    Enutrof (int Team);
    // Setters and Getters
  };

};

#endif
