// Generated by dia2code
#ifndef STATE__HERO__H
#define STATE__HERO__H


namespace state {
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class Hero - 
  class Hero : public state::MobileElement {
    // Operations
  public:
    Hero ();
    ~Hero ();
    // Setters and Getters
  };

};

#endif
