// Generated by dia2code
#ifndef STATE__HEROID__H
#define STATE__HEROID__H


namespace state {
  class Hero;
}

#include "Hero.h"

namespace state {

  enum HeroId {
    SRAM     = 1,
    IOP     = 2,
    CRA     = 3,
    FECA     = 4,
    SACRIEUR     = 5,
    ECAFLIP     = 6,
    OSAMODAS     = 7,
    XELOR     = 8,
    SADIDA     = 9,
    ENUTROF     = 10
  };

};

#endif
