// Generated by dia2code
#ifndef STATE__HERO__H
#define STATE__HERO__H


namespace state {
  class MobileElement;
}

#include "HeroId.h"
#include "MobileElement.h"
#include "HeroStatus.h"

namespace state {

  /// class Hero - 
  class Hero : public state::MobileElement {
    // Associations
    state::HeroStatus status;
    // Attributes
  protected:
    int m_xp     = 0;
    int m_level     = 0;
    // Operations
  public:
    Hero (HeroId id);
    ~Hero ();
    void LevelUp ();
    void capture ();
    int getLevel ();
    // Setters and Getters
    HeroStatus getStatus() const;
    void setStatus(HeroStatus status);
    int getM_xp() const;
    void setM_xp(int m_xp);
    int getM_level() const;
    void setM_level(int m_level);
  };

};

#endif
