// Generated by dia2code
#ifndef STATE__IOP__H
#define STATE__IOP__H


namespace state {
  class Hero;
}

#include "Hero.h"

namespace state {

  /// class Iop - 
  class Iop : public state::Hero {
    // Operations
  public:
    Iop ();
    ~Iop ();
    // Setters and Getters
  };

};

#endif
