// Generated by dia2code
#ifndef STATE__MINION__H
#define STATE__MINION__H


namespace state {
  class MobileElement;
}

#include "MobileElement.h"

namespace state {

  /// class Minion - 
  class Minion : public state::MobileElement {
    // Operations
  public:
    Minion ();
    ~Minion ();
    // Setters and Getters
  };

};

#endif
