// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H

#include <state/Element.h>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Operations
  public:
    MobileElement ();
    ~MobileElement ();
    void getStatus ();
    // Setters and Getters
  };

};

#endif
