// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Attributes
  protected:
    /// 	
    int position;
    int MP;
    int LP;
    int ATK;
    int DEF;
    int RANGE;
    // Operations
  public:
    MobileElement ();
    ~MobileElement ();
    bool const isHero ();
    int Atk (const Element& other);
    int move ();
    int setLife (int );
    int getLife ();
    // Setters and Getters
    int getPosition() const;
    void setPosition(int position);
    int getMP() const;
    void setMP(int MP);
    int getLP() const;
    void setLP(int LP);
    int getATK() const;
    void setATK(int ATK);
    int getDEF() const;
    void setDEF(int DEF);
    int getRANGE() const;
    void setRANGE(int RANGE);
  };

};

#endif
