// Generated by dia2code
#ifndef STATE__MOBILEELEMENT__H
#define STATE__MOBILEELEMENT__H


namespace state {
  class MobileElement;
  class CommandCenter;
  class Element;
}

#include "Element.h"

namespace state {

  /// class MobileElement - 
  class MobileElement : public state::Element {
    // Attributes
  protected:
    int Team;
    int Life;
    int ATK;
    int Range;
    int Movement;
    // Operations
  public:
    MobileElement ();
    ~MobileElement ();
    void Attack (MobileElement& victime);
    void Attack (CommandCenter& victime);
    bool isAlive ();
    /// 	
    /// @param damage		(???) 
    void getDamage (int damage);
    void getStatus ();
    // Setters and Getters
    int getTeam() const;
    void setTeam(int Team);
    int getLife() const;
    void setLife(int Life);
    int getATK() const;
    void setATK(int ATK);
    int getRange() const;
    void setRange(int Range);
    int getMovement() const;
    void setMovement(int Movement);
  };

};

#endif
