// Generated by dia2code
#ifndef STATE__OBSTACLE__H
#define STATE__OBSTACLE__H


namespace state {
  class StaticELement;
}

#include "ObstacleId.h"
#include "StaticELement.h"

namespace state {

  /// class Obstacle - 
  class Obstacle : public state::StaticELement {
    // Associations
    state::ObstacleId obstacleId;
    // Operations
  public:
    TypeId const getTypeId ();
    Obstacle (ObstacleId id);
    // Setters and Getters
    ObstacleId getObstacleId() const;
    void setObstacleId(ObstacleId obstacleId);
  };

};

#endif
