// Generated by dia2code
#ifndef STATE__QG__H
#define STATE__QG__H


namespace state {
  class Building;
}

#include "Building.h"

namespace state {

  /// class QG - 
  class QG : public state::Building {
    // Attributes
  protected:
    int Life;
    // Operations
  public:
    QG ();
    ~QG ();
    void getDamage (int damage);
    bool isAlive ();
    // Setters and Getters
    int getLife() const;
    void setLife(int Life);
  };

};

#endif
