// Generated by dia2code
#ifndef STATE__RACEID__H
#define STATE__RACEID__H


namespace state {

  enum RaceId {
    eni     = 1,
    enu     = 2,
    sacrieur     = 3,
    iop     = 4,
    sram     = 5
  };

};

#endif
