// Generated by dia2code
#ifndef STATE__SACRIEUR__H
#define STATE__SACRIEUR__H


namespace state {
  class Hero;
}

#include "Hero.h"

namespace state {

  /// class Sacrieur - 
  class Sacrieur : public state::Hero {
    // Operations
  public:
    Sacrieur ();
    ~Sacrieur ();
    // Setters and Getters
  };

};

#endif
