// Generated by dia2code
#ifndef STATE__SELECTEUR__H
#define STATE__SELECTEUR__H


namespace state {
  class Decor;
}

#include "Decor.h"

namespace state {

  /// class Selecteur - 
  class Selecteur : public state::Decor {
    // Operations
  public:
    Selecteur ();
    ~Selecteur ();
    // Setters and Getters
  };

};

#endif
