// Generated by dia2code
#ifndef STATE__SPACETYPEID__H
#define STATE__SPACETYPEID__H


namespace state {

  enum SpaceTypeId {
    EMPTY     = 1,
    START     = 2,
    SPAWNH     = 3,
    SPAWNM     = 4
  };

};

#endif
