// Generated by dia2code
#ifndef STATE__SRAM__H
#define STATE__SRAM__H


namespace state {
  class Hero;
}

#include "Hero.h"

namespace state {

  /// class Sram - 
  class Sram : public state::Hero {
    // Operations
  public:
    Sram ();
    ~Sram ();
    Sram (int Team);
    // Setters and Getters
  };

};

#endif
