// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H

#include <state/Element.h>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticElement - 
  class StaticElement : public state::Element {
    // Operations
  public:
    StaticElement ();
    ~StaticElement ();
    // Setters and Getters
  };

};

#endif
