// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>
#include <string>
#include <state/Element.h>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  public:
    std::vector<Element> list_element;
    std::string path;
    int enable_render;
    int  nb_hero;
    int enable_state;
    int nb_tower;
    int nb_center;
    int fin;
    int width     = 672;
    int height     = 672;
    // Operations
  public:
    State ();
    ~State ();
    void init ();
    std::vector<Element> getListElement ();
    void Update ();
    void addElement (state::Element  element);
    // Setters and Getters
  };

};

#endif
