// Generated by dia2code
#ifndef STATE__STATICELEMENT__H
#define STATE__STATICELEMENT__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class StaticELement - 
  class StaticELement : public state::Element {
    // Operations
  public:
    bool const isSpace ();
    // Setters and Getters
  };

};

#endif
