// Generated by dia2code
#ifndef STATE__STATE__H
#define STATE__STATE__H

#include <vector>

namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  /// class State - 
  class State {
    // Associations
    // Attributes
  public:
    std::vector<Element> list_element;
    // Operations
  public:
    State ();
    ~State ();
    void init ();
    std::vector<Element> getListeElement ();
    // Setters and Getters
  };

};

#endif
