// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    SPACE     = 1,
    OBSTACLE     = 2,
    COMMANDTOWER     = 3,
    QG     = 4,
    MINION     = 5,
    HERO
  };

};

#endif
