// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {
  class Element;
}

#include "Element.h"

namespace state {

  enum TypeId {
    OBSTACLE     = 1,
    COMMANDTOWER     = 2,
    SPACE     = 3,
    MINION     = 4,
    HERO     = 5,
    QG     = 6
  };

};

#endif
