// Generated by dia2code
#ifndef STATE__TYPEID__H
#define STATE__TYPEID__H


namespace state {

  enum TypeId {
    SPACE     = 1,
    OBSTACLE     = 2,
    COMMANDTOWER     = 3,
    COMMANDCENTER     = 4,
    MINION     = 5,
    ENI,
    SRAM,
    IOP,
    ENU,
    SACRI,
    COEUR,
    SELECTEUR
  };

};

#endif
