# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/home/buguet/Documents/Projet IS/plt"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/home/buguet/Documents/Projet IS/plt"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/buguet/Documents/Projet IS/plt/CMakeFiles" "/home/buguet/Documents/Projet IS/plt/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/home/buguet/Documents/Projet IS/plt/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named client

# Build rule for target.
client: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 client
.PHONY : client

# fast build rule for target.
client/fast:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/build
.PHONY : client/fast

src/client/main.o: src/client/main.cpp.o

.PHONY : src/client/main.o

# target to build an object file
src/client/main.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.o
.PHONY : src/client/main.cpp.o

src/client/main.i: src/client/main.cpp.i

.PHONY : src/client/main.i

# target to preprocess a source file
src/client/main.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.i
.PHONY : src/client/main.cpp.i

src/client/main.s: src/client/main.cpp.s

.PHONY : src/client/main.s

# target to generate assembly for a file
src/client/main.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/main.cpp.s
.PHONY : src/client/main.cpp.s

src/client/render/Render.o: src/client/render/Render.cpp.o

.PHONY : src/client/render/Render.o

# target to build an object file
src/client/render/Render.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Render.cpp.o
.PHONY : src/client/render/Render.cpp.o

src/client/render/Render.i: src/client/render/Render.cpp.i

.PHONY : src/client/render/Render.i

# target to preprocess a source file
src/client/render/Render.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Render.cpp.i
.PHONY : src/client/render/Render.cpp.i

src/client/render/Render.s: src/client/render/Render.cpp.s

.PHONY : src/client/render/Render.s

# target to generate assembly for a file
src/client/render/Render.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Render.cpp.s
.PHONY : src/client/render/Render.cpp.s

src/client/render/Textures.o: src/client/render/Textures.cpp.o

.PHONY : src/client/render/Textures.o

# target to build an object file
src/client/render/Textures.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Textures.cpp.o
.PHONY : src/client/render/Textures.cpp.o

src/client/render/Textures.i: src/client/render/Textures.cpp.i

.PHONY : src/client/render/Textures.i

# target to preprocess a source file
src/client/render/Textures.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Textures.cpp.i
.PHONY : src/client/render/Textures.cpp.i

src/client/render/Textures.s: src/client/render/Textures.cpp.s

.PHONY : src/client/render/Textures.s

# target to generate assembly for a file
src/client/render/Textures.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Textures.cpp.s
.PHONY : src/client/render/Textures.cpp.s

src/client/render/Tiles.o: src/client/render/Tiles.cpp.o

.PHONY : src/client/render/Tiles.o

# target to build an object file
src/client/render/Tiles.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Tiles.cpp.o
.PHONY : src/client/render/Tiles.cpp.o

src/client/render/Tiles.i: src/client/render/Tiles.cpp.i

.PHONY : src/client/render/Tiles.i

# target to preprocess a source file
src/client/render/Tiles.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Tiles.cpp.i
.PHONY : src/client/render/Tiles.cpp.i

src/client/render/Tiles.s: src/client/render/Tiles.cpp.s

.PHONY : src/client/render/Tiles.s

# target to generate assembly for a file
src/client/render/Tiles.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/Tiles.cpp.s
.PHONY : src/client/render/Tiles.cpp.s

src/client/render/View.o: src/client/render/View.cpp.o

.PHONY : src/client/render/View.o

# target to build an object file
src/client/render/View.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/View.cpp.o
.PHONY : src/client/render/View.cpp.o

src/client/render/View.i: src/client/render/View.cpp.i

.PHONY : src/client/render/View.i

# target to preprocess a source file
src/client/render/View.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/View.cpp.i
.PHONY : src/client/render/View.cpp.i

src/client/render/View.s: src/client/render/View.cpp.s

.PHONY : src/client/render/View.s

# target to generate assembly for a file
src/client/render/View.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/client/render/View.cpp.s
.PHONY : src/client/render/View.cpp.s

src/shared/state/Building.o: src/shared/state/Building.cpp.o

.PHONY : src/shared/state/Building.o

# target to build an object file
src/shared/state/Building.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Building.cpp.o
.PHONY : src/shared/state/Building.cpp.o

src/shared/state/Building.i: src/shared/state/Building.cpp.i

.PHONY : src/shared/state/Building.i

# target to preprocess a source file
src/shared/state/Building.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Building.cpp.i
.PHONY : src/shared/state/Building.cpp.i

src/shared/state/Building.s: src/shared/state/Building.cpp.s

.PHONY : src/shared/state/Building.s

# target to generate assembly for a file
src/shared/state/Building.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Building.cpp.s
.PHONY : src/shared/state/Building.cpp.s

src/shared/state/CommandCenter.o: src/shared/state/CommandCenter.cpp.o

.PHONY : src/shared/state/CommandCenter.o

# target to build an object file
src/shared/state/CommandCenter.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/CommandCenter.cpp.o
.PHONY : src/shared/state/CommandCenter.cpp.o

src/shared/state/CommandCenter.i: src/shared/state/CommandCenter.cpp.i

.PHONY : src/shared/state/CommandCenter.i

# target to preprocess a source file
src/shared/state/CommandCenter.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/CommandCenter.cpp.i
.PHONY : src/shared/state/CommandCenter.cpp.i

src/shared/state/CommandCenter.s: src/shared/state/CommandCenter.cpp.s

.PHONY : src/shared/state/CommandCenter.s

# target to generate assembly for a file
src/shared/state/CommandCenter.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/CommandCenter.cpp.s
.PHONY : src/shared/state/CommandCenter.cpp.s

src/shared/state/CommandTower.o: src/shared/state/CommandTower.cpp.o

.PHONY : src/shared/state/CommandTower.o

# target to build an object file
src/shared/state/CommandTower.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/CommandTower.cpp.o
.PHONY : src/shared/state/CommandTower.cpp.o

src/shared/state/CommandTower.i: src/shared/state/CommandTower.cpp.i

.PHONY : src/shared/state/CommandTower.i

# target to preprocess a source file
src/shared/state/CommandTower.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/CommandTower.cpp.i
.PHONY : src/shared/state/CommandTower.cpp.i

src/shared/state/CommandTower.s: src/shared/state/CommandTower.cpp.s

.PHONY : src/shared/state/CommandTower.s

# target to generate assembly for a file
src/shared/state/CommandTower.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/CommandTower.cpp.s
.PHONY : src/shared/state/CommandTower.cpp.s

src/shared/state/Decor.o: src/shared/state/Decor.cpp.o

.PHONY : src/shared/state/Decor.o

# target to build an object file
src/shared/state/Decor.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Decor.cpp.o
.PHONY : src/shared/state/Decor.cpp.o

src/shared/state/Decor.i: src/shared/state/Decor.cpp.i

.PHONY : src/shared/state/Decor.i

# target to preprocess a source file
src/shared/state/Decor.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Decor.cpp.i
.PHONY : src/shared/state/Decor.cpp.i

src/shared/state/Decor.s: src/shared/state/Decor.cpp.s

.PHONY : src/shared/state/Decor.s

# target to generate assembly for a file
src/shared/state/Decor.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Decor.cpp.s
.PHONY : src/shared/state/Decor.cpp.s

src/shared/state/Element.o: src/shared/state/Element.cpp.o

.PHONY : src/shared/state/Element.o

# target to build an object file
src/shared/state/Element.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Element.cpp.o
.PHONY : src/shared/state/Element.cpp.o

src/shared/state/Element.i: src/shared/state/Element.cpp.i

.PHONY : src/shared/state/Element.i

# target to preprocess a source file
src/shared/state/Element.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Element.cpp.i
.PHONY : src/shared/state/Element.cpp.i

src/shared/state/Element.s: src/shared/state/Element.cpp.s

.PHONY : src/shared/state/Element.s

# target to generate assembly for a file
src/shared/state/Element.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Element.cpp.s
.PHONY : src/shared/state/Element.cpp.s

src/shared/state/Eniripsa.o: src/shared/state/Eniripsa.cpp.o

.PHONY : src/shared/state/Eniripsa.o

# target to build an object file
src/shared/state/Eniripsa.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Eniripsa.cpp.o
.PHONY : src/shared/state/Eniripsa.cpp.o

src/shared/state/Eniripsa.i: src/shared/state/Eniripsa.cpp.i

.PHONY : src/shared/state/Eniripsa.i

# target to preprocess a source file
src/shared/state/Eniripsa.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Eniripsa.cpp.i
.PHONY : src/shared/state/Eniripsa.cpp.i

src/shared/state/Eniripsa.s: src/shared/state/Eniripsa.cpp.s

.PHONY : src/shared/state/Eniripsa.s

# target to generate assembly for a file
src/shared/state/Eniripsa.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Eniripsa.cpp.s
.PHONY : src/shared/state/Eniripsa.cpp.s

src/shared/state/Enutrof.o: src/shared/state/Enutrof.cpp.o

.PHONY : src/shared/state/Enutrof.o

# target to build an object file
src/shared/state/Enutrof.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Enutrof.cpp.o
.PHONY : src/shared/state/Enutrof.cpp.o

src/shared/state/Enutrof.i: src/shared/state/Enutrof.cpp.i

.PHONY : src/shared/state/Enutrof.i

# target to preprocess a source file
src/shared/state/Enutrof.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Enutrof.cpp.i
.PHONY : src/shared/state/Enutrof.cpp.i

src/shared/state/Enutrof.s: src/shared/state/Enutrof.cpp.s

.PHONY : src/shared/state/Enutrof.s

# target to generate assembly for a file
src/shared/state/Enutrof.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Enutrof.cpp.s
.PHONY : src/shared/state/Enutrof.cpp.s

src/shared/state/Hero.o: src/shared/state/Hero.cpp.o

.PHONY : src/shared/state/Hero.o

# target to build an object file
src/shared/state/Hero.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Hero.cpp.o
.PHONY : src/shared/state/Hero.cpp.o

src/shared/state/Hero.i: src/shared/state/Hero.cpp.i

.PHONY : src/shared/state/Hero.i

# target to preprocess a source file
src/shared/state/Hero.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Hero.cpp.i
.PHONY : src/shared/state/Hero.cpp.i

src/shared/state/Hero.s: src/shared/state/Hero.cpp.s

.PHONY : src/shared/state/Hero.s

# target to generate assembly for a file
src/shared/state/Hero.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Hero.cpp.s
.PHONY : src/shared/state/Hero.cpp.s

src/shared/state/Iop.o: src/shared/state/Iop.cpp.o

.PHONY : src/shared/state/Iop.o

# target to build an object file
src/shared/state/Iop.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Iop.cpp.o
.PHONY : src/shared/state/Iop.cpp.o

src/shared/state/Iop.i: src/shared/state/Iop.cpp.i

.PHONY : src/shared/state/Iop.i

# target to preprocess a source file
src/shared/state/Iop.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Iop.cpp.i
.PHONY : src/shared/state/Iop.cpp.i

src/shared/state/Iop.s: src/shared/state/Iop.cpp.s

.PHONY : src/shared/state/Iop.s

# target to generate assembly for a file
src/shared/state/Iop.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Iop.cpp.s
.PHONY : src/shared/state/Iop.cpp.s

src/shared/state/Minion.o: src/shared/state/Minion.cpp.o

.PHONY : src/shared/state/Minion.o

# target to build an object file
src/shared/state/Minion.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Minion.cpp.o
.PHONY : src/shared/state/Minion.cpp.o

src/shared/state/Minion.i: src/shared/state/Minion.cpp.i

.PHONY : src/shared/state/Minion.i

# target to preprocess a source file
src/shared/state/Minion.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Minion.cpp.i
.PHONY : src/shared/state/Minion.cpp.i

src/shared/state/Minion.s: src/shared/state/Minion.cpp.s

.PHONY : src/shared/state/Minion.s

# target to generate assembly for a file
src/shared/state/Minion.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Minion.cpp.s
.PHONY : src/shared/state/Minion.cpp.s

src/shared/state/MobileElement.o: src/shared/state/MobileElement.cpp.o

.PHONY : src/shared/state/MobileElement.o

# target to build an object file
src/shared/state/MobileElement.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/MobileElement.cpp.o
.PHONY : src/shared/state/MobileElement.cpp.o

src/shared/state/MobileElement.i: src/shared/state/MobileElement.cpp.i

.PHONY : src/shared/state/MobileElement.i

# target to preprocess a source file
src/shared/state/MobileElement.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/MobileElement.cpp.i
.PHONY : src/shared/state/MobileElement.cpp.i

src/shared/state/MobileElement.s: src/shared/state/MobileElement.cpp.s

.PHONY : src/shared/state/MobileElement.s

# target to generate assembly for a file
src/shared/state/MobileElement.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/MobileElement.cpp.s
.PHONY : src/shared/state/MobileElement.cpp.s

src/shared/state/Sacrieur.o: src/shared/state/Sacrieur.cpp.o

.PHONY : src/shared/state/Sacrieur.o

# target to build an object file
src/shared/state/Sacrieur.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Sacrieur.cpp.o
.PHONY : src/shared/state/Sacrieur.cpp.o

src/shared/state/Sacrieur.i: src/shared/state/Sacrieur.cpp.i

.PHONY : src/shared/state/Sacrieur.i

# target to preprocess a source file
src/shared/state/Sacrieur.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Sacrieur.cpp.i
.PHONY : src/shared/state/Sacrieur.cpp.i

src/shared/state/Sacrieur.s: src/shared/state/Sacrieur.cpp.s

.PHONY : src/shared/state/Sacrieur.s

# target to generate assembly for a file
src/shared/state/Sacrieur.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Sacrieur.cpp.s
.PHONY : src/shared/state/Sacrieur.cpp.s

src/shared/state/Sram.o: src/shared/state/Sram.cpp.o

.PHONY : src/shared/state/Sram.o

# target to build an object file
src/shared/state/Sram.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Sram.cpp.o
.PHONY : src/shared/state/Sram.cpp.o

src/shared/state/Sram.i: src/shared/state/Sram.cpp.i

.PHONY : src/shared/state/Sram.i

# target to preprocess a source file
src/shared/state/Sram.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Sram.cpp.i
.PHONY : src/shared/state/Sram.cpp.i

src/shared/state/Sram.s: src/shared/state/Sram.cpp.s

.PHONY : src/shared/state/Sram.s

# target to generate assembly for a file
src/shared/state/Sram.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/Sram.cpp.s
.PHONY : src/shared/state/Sram.cpp.s

src/shared/state/State.o: src/shared/state/State.cpp.o

.PHONY : src/shared/state/State.o

# target to build an object file
src/shared/state/State.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/State.cpp.o
.PHONY : src/shared/state/State.cpp.o

src/shared/state/State.i: src/shared/state/State.cpp.i

.PHONY : src/shared/state/State.i

# target to preprocess a source file
src/shared/state/State.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/State.cpp.i
.PHONY : src/shared/state/State.cpp.i

src/shared/state/State.s: src/shared/state/State.cpp.s

.PHONY : src/shared/state/State.s

# target to generate assembly for a file
src/shared/state/State.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/State.cpp.s
.PHONY : src/shared/state/State.cpp.s

src/shared/state/StaticElement.o: src/shared/state/StaticElement.cpp.o

.PHONY : src/shared/state/StaticElement.o

# target to build an object file
src/shared/state/StaticElement.cpp.o:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/StaticElement.cpp.o
.PHONY : src/shared/state/StaticElement.cpp.o

src/shared/state/StaticElement.i: src/shared/state/StaticElement.cpp.i

.PHONY : src/shared/state/StaticElement.i

# target to preprocess a source file
src/shared/state/StaticElement.cpp.i:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/StaticElement.cpp.i
.PHONY : src/shared/state/StaticElement.cpp.i

src/shared/state/StaticElement.s: src/shared/state/StaticElement.cpp.s

.PHONY : src/shared/state/StaticElement.s

# target to generate assembly for a file
src/shared/state/StaticElement.cpp.s:
	$(MAKE) -f CMakeFiles/client.dir/build.make CMakeFiles/client.dir/src/shared/state/StaticElement.cpp.s
.PHONY : src/shared/state/StaticElement.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... client"
	@echo "... src/client/main.o"
	@echo "... src/client/main.i"
	@echo "... src/client/main.s"
	@echo "... src/client/render/Render.o"
	@echo "... src/client/render/Render.i"
	@echo "... src/client/render/Render.s"
	@echo "... src/client/render/Textures.o"
	@echo "... src/client/render/Textures.i"
	@echo "... src/client/render/Textures.s"
	@echo "... src/client/render/Tiles.o"
	@echo "... src/client/render/Tiles.i"
	@echo "... src/client/render/Tiles.s"
	@echo "... src/client/render/View.o"
	@echo "... src/client/render/View.i"
	@echo "... src/client/render/View.s"
	@echo "... src/shared/state/Building.o"
	@echo "... src/shared/state/Building.i"
	@echo "... src/shared/state/Building.s"
	@echo "... src/shared/state/CommandCenter.o"
	@echo "... src/shared/state/CommandCenter.i"
	@echo "... src/shared/state/CommandCenter.s"
	@echo "... src/shared/state/CommandTower.o"
	@echo "... src/shared/state/CommandTower.i"
	@echo "... src/shared/state/CommandTower.s"
	@echo "... src/shared/state/Decor.o"
	@echo "... src/shared/state/Decor.i"
	@echo "... src/shared/state/Decor.s"
	@echo "... src/shared/state/Element.o"
	@echo "... src/shared/state/Element.i"
	@echo "... src/shared/state/Element.s"
	@echo "... src/shared/state/Eniripsa.o"
	@echo "... src/shared/state/Eniripsa.i"
	@echo "... src/shared/state/Eniripsa.s"
	@echo "... src/shared/state/Enutrof.o"
	@echo "... src/shared/state/Enutrof.i"
	@echo "... src/shared/state/Enutrof.s"
	@echo "... src/shared/state/Hero.o"
	@echo "... src/shared/state/Hero.i"
	@echo "... src/shared/state/Hero.s"
	@echo "... src/shared/state/Iop.o"
	@echo "... src/shared/state/Iop.i"
	@echo "... src/shared/state/Iop.s"
	@echo "... src/shared/state/Minion.o"
	@echo "... src/shared/state/Minion.i"
	@echo "... src/shared/state/Minion.s"
	@echo "... src/shared/state/MobileElement.o"
	@echo "... src/shared/state/MobileElement.i"
	@echo "... src/shared/state/MobileElement.s"
	@echo "... src/shared/state/Sacrieur.o"
	@echo "... src/shared/state/Sacrieur.i"
	@echo "... src/shared/state/Sacrieur.s"
	@echo "... src/shared/state/Sram.o"
	@echo "... src/shared/state/Sram.i"
	@echo "... src/shared/state/Sram.s"
	@echo "... src/shared/state/State.o"
	@echo "... src/shared/state/State.i"
	@echo "... src/shared/state/State.s"
	@echo "... src/shared/state/StaticElement.o"
	@echo "... src/shared/state/StaticElement.i"
	@echo "... src/shared/state/StaticElement.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

