// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H

#include <SFML/Graphics.hpp>
#include <state/State.h>

namespace state {
  class State;
};
namespace render {
  class View;
}

#include "View.h"

namespace render {

  /// class Render - 
  class Render {
    // Associations
    // Attributes
  public:
    sf::RenderWindow window;
    // Operations
  public:
    Render ();
    ~Render ();
    void init (state::State& state_game);
    void Update (state::State& state_game);
    // Setters and Getters
  };

};

#endif
