// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H

#include <SFML/Graphics.hpp>
#include <state/State.h>

namespace render {

  /// class Render - 
  class Render {
    // Attributes
  public:
    sf::RenderWindow window;
    // Operations
  public:
    Render ();
    ~Render ();
    void init (state::State state_game);
    // Setters and Getters
  };

};

#endif
