// Generated by dia2code
#ifndef RENDER__RENDER__H
#define RENDER__RENDER__H

#include <SFML/Graphics.hpp>
#include <SFML/Graphics.hpp>

namespace render {

  /// class Render - 
  class Render {
    // Attributes
  public:
    sf::RenderWindow window;
    // Operations
  public:
    Render ();
    ~Render ();
    // Setters and Getters
  };

};

#endif
