// Generated by dia2code
#ifndef RENDER__TILES__H
#define RENDER__TILES__H

#include <SFML/Graphics.hpp>
#include <string>

namespace render {

  /// class Tiles - 
  class Tiles {
    // Attributes
  public:
    const int* tiles;
    int size;
    sf::Vector2i pos_iop;
    const int* tiles_territory;
    sf::Image image;
    sf::Vector2u image_dim;
    // Operations
  public:
    void convert (std::string path);
    Tiles ();
    ~Tiles ();
    // Setters and Getters
  };

};

#endif
