// Generated by dia2code
#ifndef RENDER__VIEW__H
#define RENDER__VIEW__H

#include <SFML/Graphics.hpp>
#include <vector>
#include <state/State.h>

namespace render {
  class Textures;
};
namespace state {
  class State;
};
namespace render {
  class Tiles;
}

#include "Textures.h"
#include "state/State.h"
#include "Tiles.h"

namespace render {

  /// class View - 
  class View {
    // Associations
    // Attributes
  public:
    sf::View view;
    int type;
    std::vector<sf::Sprite> list_sprite_element;
    std::vector<Textures> list_texture;
    int nb_hero;
    int nb_tower;
    int nb_center;
    std::vector<sf::Sprite> list_sprite_decor;
    // Operations
  public:
    View ();
    ~View ();
    void init (state::State& state_game);
    void draw (sf::RenderWindow& window, const state::State state_game);
    void add_Sprite (sf::Sprite sprite);
    void Update (state::State& state_game);
    // Setters and Getters
  };

};

#endif
