// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>
#include <state/State.h>

namespace engine {
  class Command;
  class Engine;
};
namespace state {
  class State;
}

#include "engine/Command.h"
#include "state/State.h"
#include "engine/Engine.h"

namespace ai {

  /// class Ai - 
  class Ai {
    // Attributes
  public:
    int Id;
    int Team;
    std::vector<int> listElementChecked;
    std::vector<engine::Command> list_att;
    std::vector<engine::Command> list_mov;
    std::vector<int> score_att;
    std::vector<int> score_mov;
    // Operations
  public:
    virtual engine::Command play (engine::Engine& engine, int character, state::State& state) = 0;
    Ai ();
    ~Ai ();
    void init ( );
    void clearListInt (std::vector<int> score);
    // Setters and Getters
  };

};

#endif
