// Generated by dia2code
#ifndef AI__AI__H
#define AI__AI__H

#include <vector>
#include <state/State.h>

namespace engine {
  class Engine;
  class Command;
};
namespace state {
  class State;
}

namespace ai {

  /// class Ai - 
  class Ai {
    // Operations
  public:
    virtual void run (engine::Engine& engine, int character) = 0;
  protected:
    void listCommands (std::vector<engine::Command*>& list, const state::State& state, int character);
    // Setters and Getters
  };

};

#endif
