// Generated by dia2code
#ifndef AI__HEURISTICAI__H
#define AI__HEURISTICAI__H

#include <state/State.h>

namespace engine {
  class Command;
  class Engine;
};
namespace state {
  class State;
};
namespace ai {
  class Ai;
}

#include "engine/Command.h"
#include "Ai.h"

namespace ai {

  /// class HeuristicAi - 
  class HeuristicAi : public ai::Ai {
    // Operations
  public:
    HeuristicAi ();
    ~HeuristicAi ();
    HeuristicAi (int Team);
    engine::Command play (engine::Engine& engine, int character, state::State& state);
    void scor_mov (state::State& state, int character, engine::Engine& engine);
    void scor_att (state::State& state, int character);
    // Setters and Getters
  };

};

#endif
