// Generated by dia2code
#ifndef AI__MINMAX__H
#define AI__MINMAX__H

#include <engine/MoveChar.h>
#include <engine/Attack.h>
#include <vector>
#include <state/State.h>

namespace ai {
  class Node;
};
namespace state {
  class State;
};
namespace ai {
  class Ai;
}

#include "Node.h"
#include "state/State.h"
#include "Ai.h"

namespace ai {

  /// class MinMax - 
  class MinMax {
    // Attributes
  public:
    engine::MoveChar action_mov;
    engine::Attack action_att;
    std::vector<ai::Node> tree;
    state::State state_tempo;
    // Operations
  public:
    MinMax ();
    ~MinMax ();
    void create_tree (const state::State& state, int team, int id, int depth);
    void recursive (int depth, state::State& state, int depart, std::vector<engine::MoveChar> record, int ordre);
    void score (ai::Node& node, const state::State& state, int team, int id);
    int solve (const state::State& state, int team, int id, std::vector<ai::Node> tree);
    // Setters and Getters
  };

};

#endif
