// Generated by dia2code
#ifndef AI__NODE__H
#define AI__NODE__H


namespace ai {
  class MinMax;
}

#include "MinMax.h"

namespace ai {

  /// class Node - 
  class Node {
    // Attributes
  public:
    int team;
    int id;
    int depth;
    int site;
  protected:
    int score;
    int id_parent;
    int nb_child;
    int ind_sol;
    // Operations
  public:
    Node ();
    ~Node ();
    Node (int depth, int id, int team, int id_parent, int site);
    int get_ind_sol ();
    int get_score ();
    void set_score (int score);
    void set_ind_sol (int ind_sol);
    // Setters and Getters
    int getScore() const;
    void setScore(int score);
    int getId_parent() const;
    void setId_parent(int id_parent);
    int getNb_child() const;
    void setNb_child(int nb_child);
    int getInd_sol() const;
    void setInd_sol(int ind_sol);
  };

};

#endif
