// Generated by dia2code
#ifndef AI__NODE__H
#define AI__NODE__H


namespace ai {
  class MinMax;
}

#include "MinMax.h"

namespace ai {

  /// class Node - 
  class Node {
    // Attributes
  protected:
    int team;
    int score;
    int id;
    int width;
    int nb_child;
    int ind_sol;
    int depth;
    // Operations
  public:
    Node ();
    ~Node ();
    Node (int depth);
    Node (int depth, int width, int team);
    int get_ind_sol ();
    int get_score ();
    void set_score (int score);
    void set_ind_sol (int ind_sol);
    // Setters and Getters
    int getTeam() const;
    void setTeam(int team);
    int getScore() const;
    void setScore(int score);
    int getId() const;
    void setId(int id);
    int getWidth() const;
    void setWidth(int width);
    int getNb_child() const;
    void setNb_child(int nb_child);
    int getInd_sol() const;
    void setInd_sol(int ind_sol);
    int getDepth() const;
    void setDepth(int depth);
  };

};

#endif
