// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H

#include <state/State.h>

namespace engine {
  class Command;
  class Engine;
};
namespace state {
  class State;
};
namespace ai {
  class Ai;
}

#include "engine/Command.h"
#include "Ai.h"

namespace ai {

  /// class RandomAi - 
  class RandomAi : public ai::Ai {
    // Operations
  public:
    RandomAi ( );
    ~RandomAi ();
    RandomAi (int Team);
    engine::Command play (engine::Engine& engine, int character, state::State& state);
    // Setters and Getters
  };

};

#endif
