// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H


namespace engine {
  class Engine;
};
namespace ai {
  class Ai;
}

#include "Ai.h"

namespace ai {

  /// class RandomAi - 
  class RandomAi : public ai::Ai {
    // Attributes
  public:
    int RandomNumber;
    // Operations
  public:
    RandomAi ( );
    ~RandomAi ();
    void run (engine::Engine& engine, int character);
    // Setters and Getters
  };

};

#endif
