// Generated by dia2code
#ifndef AI__RANDOMAI__H
#define AI__RANDOMAI__H


namespace ai {
  class Ai;
}

#include "Ai.h"

namespace ai {

  /// class RandomAi - 
  class RandomAi : public ai::Ai {
    // Operations
  public:
    RandomAi ( );
    ~RandomAi ();
    RandomAi (int Team);
    // Setters and Getters
  };

};

#endif
