// Generated by dia2code
#ifndef ENGINE__ATTACK__H
#define ENGINE__ATTACK__H

#include <json/json.h>

namespace engine {
  class Attack;
  class Command;
};
namespace state {
  class MobileElement;
}

#include "Command.h"
#include "state/MobileElement.h"

namespace engine {

  /// class Attack - 
  class Attack : public engine::Command {
    // Operations
  public:
    ~Attack ();
    void setVictime (int d);
    void setAttaquant (int c);
    void setAttack (int c, int d);
    Attack (int c, int d);
    /// 			
    /// @param out		(???) 
    void serialize (Json::Value& out);
    Attack* deserialize (const Json::Value& in);
    // Setters and Getters
  };

};

#endif
