// Generated by dia2code
#ifndef ENGINE__ATTACK__H
#define ENGINE__ATTACK__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class Attack - 
  class Attack : public engine::Command {
    // Operations
  public:
    ~Attack ();
    void setVictime (int d);
    void setAttaquant (int c);
    void setAttack (int c, int d);
    Attack (int c, int d);
    // Setters and Getters
  };

};

#endif
