// Generated by dia2code
#ifndef ENGINE__CHECKAROUND__H
#define ENGINE__CHECKAROUND__H

#include <state/Element.h>

namespace state {
  class Element;
};
namespace engine {
  class Command;
}

#include "state/Element.h"
#include "Command.h"

namespace engine {

  /// class CheckAround - 
  class CheckAround : public engine::Command {
    // Operations
  public:
    CheckAround (int c);
    ~CheckAround ();
    void addElementChecked (state::Element e);
    void clearListelementChecked ();
    void setCheck ();
    // Setters and Getters
  };

};

#endif
