// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <state/State.h>
#include <json/json.h>

namespace state {
  class State;
};
namespace engine {
  class Engine;
}

#include "state/State.h"
#include "Engine.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Attributes
  protected:
    int Id;
    int character;
    int direction;
    int attaquant;
    int victime;
    // Operations
  public:
    Command ();
    ~Command ();
    int execute (state::State& state);
    void undo (state::State& state);
    Json::Value serialize ();
    /// 	
    /// @param in		(???) 
    void deserialize (Json::Value in);
    // Setters and Getters
    int getId() const;
    void setId(int Id);
    int getCharacter() const;
    void setCharacter(int character);
    int getDirection() const;
    void setDirection(int direction);
    int getAttaquant() const;
    void setAttaquant(int attaquant);
    int getVictime() const;
    void setVictime(int victime);
  };

};

#endif
