// Generated by dia2code
#ifndef ENGINE__COMMAND__H
#define ENGINE__COMMAND__H

#include <state/State.h>

namespace state {
  class State;
};
namespace engine {
  class Engine;
}

#include "state/State.h"
#include "Engine.h"

namespace engine {

  /// class Command - 
  class Command {
    // Associations
    // Operations
  public:
    Command ();
    ~Command ();
    virtual void execute (state::State& state) = 0;
    // Setters and Getters
  };

};

#endif
