// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>
#include <mutex>
#include <json/json.h>
#include <state/State.h>

namespace engine {
  class Command;
};
namespace state {
  class State;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  public:
    int char_sel;
    std::vector<Command> commands;
    int mov_left;
    int att_left;
    std::vector<int> list_role;
    std::vector<Command> save_commands;
    std::mutex mutex;
    bool fin_tour;
    bool engine_update;
  protected:
    Json::Value record;
    // Operations
  public:
    Engine ();
    ~Engine ();
    void addCommand (Command cmd);
    void Update (state::State& state_game, bool rollback = 0);
    void UpdateTh (state::State& state_game);
    void testInit ();
    void clearCommands ();
    void addCommands (const Json::Value& in);
    // Setters and Getters
    const Json::Value& getRecord() const;
    void setRecord(const Json::Value& record);
  };

};

#endif
