// Generated by dia2code
#ifndef ENGINE__ENGINE__H
#define ENGINE__ENGINE__H

#include <vector>
#include <state/State.h>

namespace engine {
  class Command;
};
namespace state {
  class State;
}

#include "Command.h"

namespace engine {

  /// class Engine - 
  class Engine {
    // Attributes
  public:
    int char_sel;
    std::vector<Command> commands;
    int mov_left;
    int att_left;
    // Operations
  public:
    Engine ();
    ~Engine ();
    void addCommand (Command cmd);
    void Update (state::State& state_game);
    void testInit ();
    void clearCommands ();
    // Setters and Getters
  };

};

#endif
