// Generated by dia2code
#ifndef ENGINE__MOVECHAR__H
#define ENGINE__MOVECHAR__H

#include <state/State.h>

namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveChar - 
  class MoveChar : public engine::Command {
    // Operations
  public:
    MoveChar ();
    ~MoveChar ();
    void Move (state::State& state, int Direction);
    // Setters and Getters
  };

};

#endif
