// Generated by dia2code
#ifndef ENGINE__MOVECHAR__H
#define ENGINE__MOVECHAR__H


namespace engine {
  class Command;
}

#include "Command.h"

namespace engine {

  /// class MoveChar - 
  class MoveChar : public engine::Command {
    // Operations
  public:
    MoveChar (int c, int d);
    ~MoveChar ();
    // Setters and Getters
  };

};

#endif
