// Generated by dia2code
#ifndef ENGINE__MOVECHAR__H
#define ENGINE__MOVECHAR__H


namespace state {
  class MobileElement;
};
namespace engine {
  class Command;
}

#include "state/MobileElement.h"
#include "Command.h"

namespace engine {

  /// class MoveChar - 
  class MoveChar : public engine::Command {
    // Operations
  public:
    MoveChar ();
    ~MoveChar ();
    void Move (state::MobileElement  perso, int Direction);
    // Setters and Getters
  };

};

#endif
