// Generated by dia2code
#ifndef SERVER__COMMAND__H
#define SERVER__COMMAND__H


namespace server {

  /// class Command - 
  class Command {
    // Attributes
  public:
    string Id;
    int character;
    int direction;
    int attaquant;
    int victime;
    // Operations
  public:
    User (string name);
    // Setters and Getters
  };

};

#endif
