// Generated by dia2code
#ifndef SERVER__COMMANDDB__H
#define SERVER__COMMANDDB__H


namespace server {
  class Command;
}

#include "Command.h"

namespace server {

  /// class CommandDB - 
  class CommandDB {
    // Associations
    // Attributes
  protected:
    int idseq;
    map<int,unique_ptr<Command> > Commands;
    // Operations
  public:
    CommandDB ();
    const Command* getCommand (int id) const;
    int addCommand (unique_ptr<Command> command);
    void setCommand (int id, unique_ptr<Command> command);
    void removeCommand (int id);
    // Setters and Getters
    int getIdseq() const;
    void setIdseq(int idseq);
    const map<int,unique_ptr<Command> >& getCommands() const;
    void setCommands(const map<int,unique_ptr<Command> >& Commands);
  };

};

#endif
