// Generated by dia2code
#ifndef SERVER__SERVICEEXCEPTION__H
#define SERVER__SERVICEEXCEPTION__H

<<<<<<< HEAD
=======
#include <string>
>>>>>>> 5461db31592b35211a8117fbef4bd86cd123af8a

namespace server {
  class AbstractService;
}

#include "HttpStatus.h"
#include "AbstractService.h"

namespace server {

  /// class ServiceException - 
  class ServiceException {
    // Associations
    server::HttpStatus httpStatus;
    // Attributes
  protected:
<<<<<<< HEAD
    string msg;
=======
    std::string msg;
>>>>>>> 5461db31592b35211a8117fbef4bd86cd123af8a
    // Operations
  public:
    ServiceException (HttpStatus status, string msg);
    HttpStatus status () const;
    const char* what () const;
    // Setters and Getters
    HttpStatus getHttpStatus() const;
    void setHttpStatus(HttpStatus httpStatus);
<<<<<<< HEAD
    const string& getMsg() const;
    void setMsg(const string& msg);
=======
    const std::string& getMsg() const;
    void setMsg(const std::string& msg);
>>>>>>> 5461db31592b35211a8117fbef4bd86cd123af8a
  };

};

#endif
