// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H

#include <string>

namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    std::string name;
    bool free     = true;
    // Operations
  public:
    User (string name, int age);
    // Setters and Getters
  };

};

#endif
