// Generated by dia2code
#ifndef SERVER__USER__H
#define SERVER__USER__H


namespace server {

  /// class User - 
  class User {
    // Attributes
  public:
    string name;
    // Operations
  public:
    User (string name);
    // Setters and Getters
  };

};

#endif
